### ISSUE TITLE
error in building 

### ISSUE THREAD

**Issue by tlosm** [mamedev/dosplay#1]
hello i have this error when building on Be machine 
OS Linux (ubuntu mate 16.10)

Compiling projects/dosplay/src/dosplay/main.cpp...
../../../../../projects/dosplay/src/dosplay/main.cpp:96:36: error: variable or field ‘layout_file_cb’ declared void
 void emulator_info::layout_file_cb(xml_data_node &layout) { }
                                    ^~~~~~~~~~~~~
../../../../../projects/dosplay/src/dosplay/main.cpp:96:36: error: ‘xml_data_node’ was not declared in this scope
../../../../../projects/dosplay/src/dosplay/main.cpp:96:51: error: ‘layout’ was not declared in this scope
 void emulator_info::layout_file_cb(xml_data_node &layout) { }
                                                   ^~~~~~
dosplay.make:282: recipe for target 'obj/Release/projects/dosplay/src/dosplay/main.o' failed
make[2]: *** [obj/Release/projects/dosplay/src/dosplay/main.o] Error 1
make[2]: *** Waiting for unfinished jobs....

Thanks 
Luigi

**Comment by mmicko** [comment]
Thanks. Fixed now

**Comment by tlosm** [comment]
Hi mmicko probably there is an endianess on Be dont build 

In file included from ../../../../../3rdparty/bgfx/examples/common/bgfx_utils.cpp:29:0:
../../../../../3rdparty/bgfx/3rdparty/tinyexr/tinyexr.h:796:52: error: "MINIZ_X86_OR_X64_CPU" is not defined [-Werror=undef]
 #if (__BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__) || MINIZ_X86_OR_X64_CPU
                                                    ^~~~~~~~~~~~~~~~~~~~
../../../../../3rdparty/bgfx/3rdparty/tinyexr/tinyexr.h:802:5: error: "MINIZ_X86_OR_X64_CPU" is not defined [-Werror=undef]
 #if MINIZ_X86_OR_X64_CPU
     ^~~~~~~~~~~~~~~~~~~~
In file included from ../../../../../3rdparty/bgfx/examples/common/bgfx_utils.cpp:29:0:
../../../../../3rdparty/bgfx/3rdparty/tinyexr/tinyexr.h:1832:5: error: "MINIZ_USE_UNALIGNED_LOADS_AND_STORES" is not defined [-Werror=undef]
 #if MINIZ_USE_UNALIGNED_LOADS_AND_STORES && MINIZ_LITTLE_ENDIAN
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../../3rdparty/bgfx/3rdparty/tinyexr/tinyexr.h:2787:5: error: "MINIZ_USE_UNALIGNED_LOADS_AND_STORES" is not defined [-Werror=undef]
 #if MINIZ_USE_UNALIGNED_LOADS_AND_STORES
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../../3rdparty/bgfx/3rdparty/tinyexr/tinyexr.h:3387:5: error: "MINIZ_USE_UNALIGNED_LOADS_AND_STORES" is not defined [-Werror=undef]
 #if MINIZ_USE_UNALIGNED_LOADS_AND_STORES && MINIZ_LITTLE_ENDIAN && \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../../3rdparty/bgfx/3rdparty/tinyexr/tinyexr.h:3664:5: error: "MINIZ_USE_UNALIGNED_LOADS_AND_STORES" is not defined [-Werror=undef]
 #if MINIZ_USE_UNALIGNED_LOADS_AND_STORES
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../../3rdparty/bgfx/3rdparty/tinyexr/tinyexr.h:3763:5: error: "MINIZ_USE_UNALIGNED_LOADS_AND_STORES" is not defined [-Werror=undef]
 #if MINIZ_USE_UNALIGNED_LOADS_AND_STORES && MINIZ_LITTLE_ENDIAN
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../../3rdparty/bgfx/3rdparty/tinyexr/tinyexr.h:4184:5: error: "MINIZ_USE_UNALIGNED_LOADS_AND_STORES" is not defined [-Werror=undef]
 #if MINIZ_USE_UNALIGNED_LOADS_AND_STORES && MINIZ_LITTLE_ENDIAN
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../../3rdparty/bgfx/3rdparty/tinyexr/tinyexr.h:6955:5: error: "MINIZ_LITTLE_ENDIAN" is not defined [-Werror=undef]
 #if MINIZ_LITTLE_ENDIAN
     ^~~~~~~~~~~~~~~~~~~
../../../../../3rdparty/bgfx/3rdparty/tinyexr/tinyexr.h:6975:5: error: "MINIZ_LITTLE_ENDIAN" is not defined [-Werror=undef]
 #if MINIZ_LITTLE_ENDIAN
     ^~~~~~~~~~~~~~~~~~~
../../../../../3rdparty/bgfx/3rdparty/tinyexr/tinyexr.h:8882:6: error: "MINIZ_LITTLE_ENDIAN" is not defined [-Werror=undef]
 #if !MINIZ_LITTLE_ENDIAN
      ^~~~~~~~~~~~~~~~~~~
../../../../../3rdparty/bgfx/3rdparty/tinyexr/tinyexr.h:8995:6: error: "MINIZ_LITTLE_ENDIAN" is not defined [-Werror=undef]
 #if !MINIZ_LITTLE_ENDIAN
      ^~~~~~~~~~~~~~~~~~~
